name: 'Build Example mousekeyspr'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR\n#define MIRYOKU_KLUDGE_DOUBLETAPBOOT"]'
      kconfig: '[""]'
      branches: '["zmkfirmware/zmk/main ftc/zmk/mouse-ftc"]'
